service: caucsim-backend

provider:
  name: aws
  runtime: nodejs20.x  # Change from 22.x to 20.x
  region: eu-west-2
  memorySize: 512
  stage: 'prod'    
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  environment:
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME, ''}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID, ''}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID, ''}
    DIGITALOCEAN_TOKEN: ${env:DIGITALOCEAN_TOKEN, ''}
    DIGITALOCEAN_PROJECT_ID: ${env:DIGITALOCEAN_PROJECT_ID, ''}
    DIGITALOCEAN_SSH_KEY_FP: ${env:DIGITALOCEAN_SSH_KEY_FP, ''}
    DIGITALOCEAN_SNAPSHOT_NAME: ${env:DIGITALOCEAN_SNAPSHOT_NAME, 'openfoam-base'}
    DIGITALOCEAN_REGION: ${env:DIGITALOCEAN_REGION, 'lon1'}
    DIGITALOCEAN_SIZE: ${env:DIGITALOCEAN_SIZE, 'gd-16vcpu-64gb'}
    APP_CALLBACK_URL: ${env:APP_CALLBACK_URL, ''}

functions:
  api:
    handler: app.handler