#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

NPROCS=$(getNumberOfProcessors)

echo "==> surfaceFeatures"
surfaceFeatures 2>&1 | tee log.surfaceFeatures


echo "==> blockMesh"
blockMesh 2>&1 | tee log.blockMesh

echo "==> decomposePar"
decomposePar -copyZero 2>&1 | tee log.decomposePar

echo "==> snappyHexMesh"
mpirun -np $NPROCS snappyHexMesh -overwrite -parallel 2>&1 | tee log.snappyHexMesh

echo "==> patchSummary"
mpirun -np $NPROCS patchSummary -parallel 2>&1 | tee log.patchSummary

echo "==> potentialFoam"
mpirun -np $NPROCS potentialFoam -parallel 2>&1 | tee log.potentialFoam

echo "==> foamRun"
mpirun -np $NPROCS foamRun -parallel 2>&1 | tee log.foamRun

echo "==> reconstructPar"
reconstructPar -latestTime 2>&1 | tee log.reconstructPar
